### ISSUE TITLE
rtweet creator approves!

### ISSUE THREAD

**Issue by mkearney** [knapply/tweetio#37]
This is cool and your depiction of at least rtweet's stream limitations is fair. I'm excited to follow your work!

**Comment by knapply** [comment]
@mkearney Thank you for the endorsement!

If you hadn't already come up with a way to sensibly structure tweets in R, this never would've happened.

I gave a lot of praise to rtweet in a previous README that was lost among chaotic commits... 
https://github.com/knapply/tweetio/blob/7c5fb39b80c355e01d937ea87a59eceeab0d9154/README.Rmd#L47

I'll make sure it gets back in there once I can work on this again.

If there's anything here you'd like rtweet to have, please let me know. Thanks for all your work!
